import streamlit as st
import pandas as pd
from pathlib import Path

st.set_page_config(page_title="Cellarm ASR POC", layout="wide")

st.title("🧬 Cellarm ASR POC: Enzyme Engineering Dashboard")
st.markdown("Welcome to the Ancestral Sequence Reconstruction Proof of Concept dashboard! Here you can view the final engineered candidates generated by our AI pipeline.")

st.header("🏆 Top Ranked Candidates")
st.markdown("These candidates have been ranked by our hybrid AI scoring pipeline (combining ESM-2 structural similarity, ESMFold confidence, and sequence conservation).")

# Load candidate ranking CSV
csv_path = Path("reports/candidate_ranking.csv")
if csv_path.exists():
    df = pd.read_csv(csv_path)
    # Display the dataframe nicely
    st.dataframe(df, use_container_width=True)
else:
    st.warning("Candidate ranking CSV not found! Have you run the pipeline?")

st.divider()

st.header("📄 Scientific Report & Hypotheses")
st.markdown("Below is the LLM-generated scientific analysis explaining *why* these candidates were selected and the evolutionary rationale behind them.")

report_path = Path("reports/scientific_report.md")
if report_path.exists():
    report_content = report_path.read_text(encoding="utf-8")
    with st.expander("View Full Scientific Report", expanded=True):
        st.markdown(report_content)
else:
    st.warning("Scientific report not found! Have you run the pipeline?")
